#playbook.yml
---
- hosts: all
  tasks:
  - name: 1. installing docker
    apt:
      name: docker
      state: present
  - name: 2. installing docker-compose
    apt:
      name: docker-compose
      state: present
  - name: 3. creating minecraft and plugins directory
    file:
      path: /home/Minecraft/plugins
      state: directory
  - name: 4. creating docker volume minecraftdata
    docker_volume:
      name: minecraftdata
  - name: 5. running docker-compose.yml
